/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GameServerStatus is the status for a GameServer resource. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServer
 */
@ApiModel(description = "GameServerStatus is the status for a GameServer resource. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServer")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class TheStatusValuesForTheGameServer {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_NODE_NAME = "nodeName";
  @SerializedName(SERIALIZED_NAME_NODE_NAME)
  private String nodeName;

  public static final String SERIALIZED_NAME_PLAYERS = "players";
  @SerializedName(SERIALIZED_NAME_PLAYERS)
  private Object players;

  public static final String SERIALIZED_NAME_PORTS = "ports";
  @SerializedName(SERIALIZED_NAME_PORTS)
  private Object ports;

  public static final String SERIALIZED_NAME_RESERVED_UNTIL = "reservedUntil";
  @SerializedName(SERIALIZED_NAME_RESERVED_UNTIL)
  private Object reservedUntil;

  /**
   * Gets or Sets state
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    PORTALLOCATION("PortAllocation"),
    
    CREATING("Creating"),
    
    STARTING("Starting"),
    
    SCHEDULED("Scheduled"),
    
    REQUESTREADY("RequestReady"),
    
    READY("Ready"),
    
    SHUTDOWN("Shutdown"),
    
    ERROR("Error"),
    
    UNHEALTHY("Unhealthy"),
    
    RESERVED("Reserved"),
    
    ALLOCATED("Allocated");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private StateEnum state;


  public TheStatusValuesForTheGameServer address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public TheStatusValuesForTheGameServer nodeName(String nodeName) {
    
    this.nodeName = nodeName;
    return this;
  }

   /**
   * Get nodeName
   * @return nodeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNodeName() {
    return nodeName;
  }


  public void setNodeName(String nodeName) {
    this.nodeName = nodeName;
  }


  public TheStatusValuesForTheGameServer players(Object players) {
    
    this.players = players;
    return this;
  }

   /**
   * Get players
   * @return players
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getPlayers() {
    return players;
  }


  public void setPlayers(Object players) {
    this.players = players;
  }


  public TheStatusValuesForTheGameServer ports(Object ports) {
    
    this.ports = ports;
    return this;
  }

   /**
   * Get ports
   * @return ports
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getPorts() {
    return ports;
  }


  public void setPorts(Object ports) {
    this.ports = ports;
  }


  public TheStatusValuesForTheGameServer reservedUntil(Object reservedUntil) {
    
    this.reservedUntil = reservedUntil;
    return this;
  }

   /**
   * Get reservedUntil
   * @return reservedUntil
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getReservedUntil() {
    return reservedUntil;
  }


  public void setReservedUntil(Object reservedUntil) {
    this.reservedUntil = reservedUntil;
  }


  public TheStatusValuesForTheGameServer state(StateEnum state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StateEnum getState() {
    return state;
  }


  public void setState(StateEnum state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TheStatusValuesForTheGameServer theStatusValuesForTheGameServer = (TheStatusValuesForTheGameServer) o;
    return Objects.equals(this.address, theStatusValuesForTheGameServer.address) &&
        Objects.equals(this.nodeName, theStatusValuesForTheGameServer.nodeName) &&
        Objects.equals(this.players, theStatusValuesForTheGameServer.players) &&
        Objects.equals(this.ports, theStatusValuesForTheGameServer.ports) &&
        Objects.equals(this.reservedUntil, theStatusValuesForTheGameServer.reservedUntil) &&
        Objects.equals(this.state, theStatusValuesForTheGameServer.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, nodeName, players, ports, reservedUntil, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TheStatusValuesForTheGameServer {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    nodeName: ").append(toIndentedString(nodeName)).append("\n");
    sb.append("    players: ").append(toIndentedString(players)).append("\n");
    sb.append("    ports: ").append(toIndentedString(ports)).append("\n");
    sb.append("    reservedUntil: ").append(toIndentedString(reservedUntil)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

