/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.agones.models.V1FleetSpecStrategy;
import dev.agones.models.V1GameServerSetSpecTemplate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FleetSpec is the spec for a Fleet. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.Fleet
 */
@ApiModel(description = "FleetSpec is the spec for a Fleet. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.Fleet")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1FleetSpec {
  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  /**
   * Gets or Sets scheduling
   */
  @JsonAdapter(SchedulingEnum.Adapter.class)
  public enum SchedulingEnum {
    PACKED("Packed"),
    
    DISTRIBUTED("Distributed");

    private String value;

    SchedulingEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SchedulingEnum fromValue(String value) {
      for (SchedulingEnum b : SchedulingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SchedulingEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SchedulingEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SchedulingEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SchedulingEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SCHEDULING = "scheduling";
  @SerializedName(SERIALIZED_NAME_SCHEDULING)
  private SchedulingEnum scheduling;

  public static final String SERIALIZED_NAME_STRATEGY = "strategy";
  @SerializedName(SERIALIZED_NAME_STRATEGY)
  private V1FleetSpecStrategy strategy;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private V1GameServerSetSpecTemplate template;


  public V1FleetSpec replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Get replicas
   * minimum: 0
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1FleetSpec scheduling(SchedulingEnum scheduling) {
    
    this.scheduling = scheduling;
    return this;
  }

   /**
   * Get scheduling
   * @return scheduling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SchedulingEnum getScheduling() {
    return scheduling;
  }


  public void setScheduling(SchedulingEnum scheduling) {
    this.scheduling = scheduling;
  }


  public V1FleetSpec strategy(V1FleetSpecStrategy strategy) {
    
    this.strategy = strategy;
    return this;
  }

   /**
   * Get strategy
   * @return strategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1FleetSpecStrategy getStrategy() {
    return strategy;
  }


  public void setStrategy(V1FleetSpecStrategy strategy) {
    this.strategy = strategy;
  }


  public V1FleetSpec template(V1GameServerSetSpecTemplate template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(required = true, value = "")

  public V1GameServerSetSpecTemplate getTemplate() {
    return template;
  }


  public void setTemplate(V1GameServerSetSpecTemplate template) {
    this.template = template;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1FleetSpec v1FleetSpec = (V1FleetSpec) o;
    return Objects.equals(this.replicas, v1FleetSpec.replicas) &&
        Objects.equals(this.scheduling, v1FleetSpec.scheduling) &&
        Objects.equals(this.strategy, v1FleetSpec.strategy) &&
        Objects.equals(this.template, v1FleetSpec.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(replicas, scheduling, strategy, template);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1FleetSpec {\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    scheduling: ").append(toIndentedString(scheduling)).append("\n");
    sb.append("    strategy: ").append(toIndentedString(strategy)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

