/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.agones.models.V1FleetAutoscalerSpecPolicy;
import dev.agones.models.V1FleetAutoscalerSpecSync;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FleetAutoscalerSpec is the spec for a Fleet Scaler. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.FleetAutoscaler
 */
@ApiModel(description = "FleetAutoscalerSpec is the spec for a Fleet Scaler. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.FleetAutoscaler")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1FleetAutoscalerSpec {
  public static final String SERIALIZED_NAME_FLEET_NAME = "fleetName";
  @SerializedName(SERIALIZED_NAME_FLEET_NAME)
  private String fleetName;

  public static final String SERIALIZED_NAME_POLICY = "policy";
  @SerializedName(SERIALIZED_NAME_POLICY)
  private V1FleetAutoscalerSpecPolicy policy;

  public static final String SERIALIZED_NAME_SYNC = "sync";
  @SerializedName(SERIALIZED_NAME_SYNC)
  private V1FleetAutoscalerSpecSync sync;


  public V1FleetAutoscalerSpec fleetName(String fleetName) {
    
    this.fleetName = fleetName;
    return this;
  }

   /**
   * Get fleetName
   * @return fleetName
  **/
  @ApiModelProperty(required = true, value = "")

  public String getFleetName() {
    return fleetName;
  }


  public void setFleetName(String fleetName) {
    this.fleetName = fleetName;
  }


  public V1FleetAutoscalerSpec policy(V1FleetAutoscalerSpecPolicy policy) {
    
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @ApiModelProperty(required = true, value = "")

  public V1FleetAutoscalerSpecPolicy getPolicy() {
    return policy;
  }


  public void setPolicy(V1FleetAutoscalerSpecPolicy policy) {
    this.policy = policy;
  }


  public V1FleetAutoscalerSpec sync(V1FleetAutoscalerSpecSync sync) {
    
    this.sync = sync;
    return this;
  }

   /**
   * Get sync
   * @return sync
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1FleetAutoscalerSpecSync getSync() {
    return sync;
  }


  public void setSync(V1FleetAutoscalerSpecSync sync) {
    this.sync = sync;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1FleetAutoscalerSpec v1FleetAutoscalerSpec = (V1FleetAutoscalerSpec) o;
    return Objects.equals(this.fleetName, v1FleetAutoscalerSpec.fleetName) &&
        Objects.equals(this.policy, v1FleetAutoscalerSpec.policy) &&
        Objects.equals(this.sync, v1FleetAutoscalerSpec.sync);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fleetName, policy, sync);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1FleetAutoscalerSpec {\n");
    sb.append("    fleetName: ").append(toIndentedString(fleetName)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    sync: ").append(toIndentedString(sync)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

