/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FleetAutoscalerStatus defines the current status of a FleetAutoscaler. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.FleetAutoscaler
 */
@ApiModel(description = "FleetAutoscalerStatus defines the current status of a FleetAutoscaler. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.FleetAutoscaler")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1FleetAutoscalerStatus {
  public static final String SERIALIZED_NAME_ABLE_TO_SCALE = "ableToScale";
  @SerializedName(SERIALIZED_NAME_ABLE_TO_SCALE)
  private Boolean ableToScale;

  public static final String SERIALIZED_NAME_CURRENT_REPLICAS = "currentReplicas";
  @SerializedName(SERIALIZED_NAME_CURRENT_REPLICAS)
  private Integer currentReplicas;

  public static final String SERIALIZED_NAME_DESIRED_REPLICAS = "desiredReplicas";
  @SerializedName(SERIALIZED_NAME_DESIRED_REPLICAS)
  private Integer desiredReplicas;

  public static final String SERIALIZED_NAME_LAST_SCALE_TIME = "lastScaleTime";
  @SerializedName(SERIALIZED_NAME_LAST_SCALE_TIME)
  private Object lastScaleTime;

  public static final String SERIALIZED_NAME_SCALING_LIMITED = "scalingLimited";
  @SerializedName(SERIALIZED_NAME_SCALING_LIMITED)
  private Boolean scalingLimited;


  public V1FleetAutoscalerStatus ableToScale(Boolean ableToScale) {
    
    this.ableToScale = ableToScale;
    return this;
  }

   /**
   * Get ableToScale
   * @return ableToScale
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAbleToScale() {
    return ableToScale;
  }


  public void setAbleToScale(Boolean ableToScale) {
    this.ableToScale = ableToScale;
  }


  public V1FleetAutoscalerStatus currentReplicas(Integer currentReplicas) {
    
    this.currentReplicas = currentReplicas;
    return this;
  }

   /**
   * Get currentReplicas
   * @return currentReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCurrentReplicas() {
    return currentReplicas;
  }


  public void setCurrentReplicas(Integer currentReplicas) {
    this.currentReplicas = currentReplicas;
  }


  public V1FleetAutoscalerStatus desiredReplicas(Integer desiredReplicas) {
    
    this.desiredReplicas = desiredReplicas;
    return this;
  }

   /**
   * Get desiredReplicas
   * @return desiredReplicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDesiredReplicas() {
    return desiredReplicas;
  }


  public void setDesiredReplicas(Integer desiredReplicas) {
    this.desiredReplicas = desiredReplicas;
  }


  public V1FleetAutoscalerStatus lastScaleTime(Object lastScaleTime) {
    
    this.lastScaleTime = lastScaleTime;
    return this;
  }

   /**
   * Get lastScaleTime
   * @return lastScaleTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLastScaleTime() {
    return lastScaleTime;
  }


  public void setLastScaleTime(Object lastScaleTime) {
    this.lastScaleTime = lastScaleTime;
  }


  public V1FleetAutoscalerStatus scalingLimited(Boolean scalingLimited) {
    
    this.scalingLimited = scalingLimited;
    return this;
  }

   /**
   * Get scalingLimited
   * @return scalingLimited
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getScalingLimited() {
    return scalingLimited;
  }


  public void setScalingLimited(Boolean scalingLimited) {
    this.scalingLimited = scalingLimited;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1FleetAutoscalerStatus v1FleetAutoscalerStatus = (V1FleetAutoscalerStatus) o;
    return Objects.equals(this.ableToScale, v1FleetAutoscalerStatus.ableToScale) &&
        Objects.equals(this.currentReplicas, v1FleetAutoscalerStatus.currentReplicas) &&
        Objects.equals(this.desiredReplicas, v1FleetAutoscalerStatus.desiredReplicas) &&
        Objects.equals(this.lastScaleTime, v1FleetAutoscalerStatus.lastScaleTime) &&
        Objects.equals(this.scalingLimited, v1FleetAutoscalerStatus.scalingLimited);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ableToScale, currentReplicas, desiredReplicas, lastScaleTime, scalingLimited);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1FleetAutoscalerStatus {\n");
    sb.append("    ableToScale: ").append(toIndentedString(ableToScale)).append("\n");
    sb.append("    currentReplicas: ").append(toIndentedString(currentReplicas)).append("\n");
    sb.append("    desiredReplicas: ").append(toIndentedString(desiredReplicas)).append("\n");
    sb.append("    lastScaleTime: ").append(toIndentedString(lastScaleTime)).append("\n");
    sb.append("    scalingLimited: ").append(toIndentedString(scalingLimited)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

