/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.agones.models.V1GameServerSpecTemplateSpecLifecyclePostStartHttpGetHttpHeaders;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HTTPGet specifies the http request to perform.
 */
@ApiModel(description = "HTTPGet specifies the http request to perform.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet {
  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_HTTP_HEADERS = "httpHeaders";
  @SerializedName(SERIALIZED_NAME_HTTP_HEADERS)
  private List<V1GameServerSpecTemplateSpecLifecyclePostStartHttpGetHttpHeaders> httpHeaders = null;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Object port;

  public static final String SERIALIZED_NAME_SCHEME = "scheme";
  @SerializedName(SERIALIZED_NAME_SCHEME)
  private String scheme;


  public V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * Host name to connect to, defaults to the pod IP. You probably want to set \&quot;Host\&quot; in httpHeaders instead.
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Host name to connect to, defaults to the pod IP. You probably want to set \"Host\" in httpHeaders instead.")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet httpHeaders(List<V1GameServerSpecTemplateSpecLifecyclePostStartHttpGetHttpHeaders> httpHeaders) {
    
    this.httpHeaders = httpHeaders;
    return this;
  }

  public V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet addHttpHeadersItem(V1GameServerSpecTemplateSpecLifecyclePostStartHttpGetHttpHeaders httpHeadersItem) {
    if (this.httpHeaders == null) {
      this.httpHeaders = new ArrayList<>();
    }
    this.httpHeaders.add(httpHeadersItem);
    return this;
  }

   /**
   * Custom headers to set in the request. HTTP allows repeated headers.
   * @return httpHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Custom headers to set in the request. HTTP allows repeated headers.")

  public List<V1GameServerSpecTemplateSpecLifecyclePostStartHttpGetHttpHeaders> getHttpHeaders() {
    return httpHeaders;
  }


  public void setHttpHeaders(List<V1GameServerSpecTemplateSpecLifecyclePostStartHttpGetHttpHeaders> httpHeaders) {
    this.httpHeaders = httpHeaders;
  }


  public V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Path to access on the HTTP server.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Path to access on the HTTP server.")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet port(Object port) {
    
    this.port = port;
    return this;
  }

   /**
   * Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
   * @return port
  **/
  @ApiModelProperty(required = true, value = "Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.")

  public Object getPort() {
    return port;
  }


  public void setPort(Object port) {
    this.port = port;
  }


  public V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet scheme(String scheme) {
    
    this.scheme = scheme;
    return this;
  }

   /**
   * Scheme to use for connecting to the host. Defaults to HTTP.  
   * @return scheme
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Scheme to use for connecting to the host. Defaults to HTTP.  ")

  public String getScheme() {
    return scheme;
  }


  public void setScheme(String scheme) {
    this.scheme = scheme;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet v1GameServerSpecTemplateSpecLifecyclePostStartHttpGet = (V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet) o;
    return Objects.equals(this.host, v1GameServerSpecTemplateSpecLifecyclePostStartHttpGet.host) &&
        Objects.equals(this.httpHeaders, v1GameServerSpecTemplateSpecLifecyclePostStartHttpGet.httpHeaders) &&
        Objects.equals(this.path, v1GameServerSpecTemplateSpecLifecyclePostStartHttpGet.path) &&
        Objects.equals(this.port, v1GameServerSpecTemplateSpecLifecyclePostStartHttpGet.port) &&
        Objects.equals(this.scheme, v1GameServerSpecTemplateSpecLifecyclePostStartHttpGet.scheme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(host, httpHeaders, path, port, scheme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GameServerSpecTemplateSpecLifecyclePostStartHttpGet {\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    httpHeaders: ").append(toIndentedString(httpHeaders)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    scheme: ").append(toIndentedString(scheme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

