/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.agones.models.HealthCheckingForTheRunningGameServer;
import dev.agones.models.ParametersForTheSDKServerSidecar;
import dev.agones.models.V1GameServerSpecTemplate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GameServerSpec is the spec for a GameServer resource. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServer
 */
@ApiModel(description = "GameServerSpec is the spec for a GameServer resource. More info: https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServer")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1GameServerSpec {
  public static final String SERIALIZED_NAME_CONTAINER = "container";
  @SerializedName(SERIALIZED_NAME_CONTAINER)
  private String container;

  public static final String SERIALIZED_NAME_HEALTH = "health";
  @SerializedName(SERIALIZED_NAME_HEALTH)
  private HealthCheckingForTheRunningGameServer health;

  public static final String SERIALIZED_NAME_PLAYERS = "players";
  @SerializedName(SERIALIZED_NAME_PLAYERS)
  private Object players;

  public static final String SERIALIZED_NAME_PORTS = "ports";
  @SerializedName(SERIALIZED_NAME_PORTS)
  private Object ports;

  /**
   * Gets or Sets scheduling
   */
  @JsonAdapter(SchedulingEnum.Adapter.class)
  public enum SchedulingEnum {
    PACKED("Packed"),
    
    DISTRIBUTED("Distributed");

    private String value;

    SchedulingEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SchedulingEnum fromValue(String value) {
      for (SchedulingEnum b : SchedulingEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SchedulingEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SchedulingEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SchedulingEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SchedulingEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SCHEDULING = "scheduling";
  @SerializedName(SERIALIZED_NAME_SCHEDULING)
  private SchedulingEnum scheduling;

  public static final String SERIALIZED_NAME_SDK_SERVER = "sdkServer";
  @SerializedName(SERIALIZED_NAME_SDK_SERVER)
  private ParametersForTheSDKServerSidecar sdkServer;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private V1GameServerSpecTemplate template;


  public V1GameServerSpec container(String container) {
    
    this.container = container;
    return this;
  }

   /**
   * if there is more than one container, specify which one is the game server
   * @return container
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "if there is more than one container, specify which one is the game server")

  public String getContainer() {
    return container;
  }


  public void setContainer(String container) {
    this.container = container;
  }


  public V1GameServerSpec health(HealthCheckingForTheRunningGameServer health) {
    
    this.health = health;
    return this;
  }

   /**
   * Get health
   * @return health
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HealthCheckingForTheRunningGameServer getHealth() {
    return health;
  }


  public void setHealth(HealthCheckingForTheRunningGameServer health) {
    this.health = health;
  }


  public V1GameServerSpec players(Object players) {
    
    this.players = players;
    return this;
  }

   /**
   * Get players
   * @return players
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getPlayers() {
    return players;
  }


  public void setPlayers(Object players) {
    this.players = players;
  }


  public V1GameServerSpec ports(Object ports) {
    
    this.ports = ports;
    return this;
  }

   /**
   * Get ports
   * @return ports
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getPorts() {
    return ports;
  }


  public void setPorts(Object ports) {
    this.ports = ports;
  }


  public V1GameServerSpec scheduling(SchedulingEnum scheduling) {
    
    this.scheduling = scheduling;
    return this;
  }

   /**
   * Get scheduling
   * @return scheduling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SchedulingEnum getScheduling() {
    return scheduling;
  }


  public void setScheduling(SchedulingEnum scheduling) {
    this.scheduling = scheduling;
  }


  public V1GameServerSpec sdkServer(ParametersForTheSDKServerSidecar sdkServer) {
    
    this.sdkServer = sdkServer;
    return this;
  }

   /**
   * Get sdkServer
   * @return sdkServer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ParametersForTheSDKServerSidecar getSdkServer() {
    return sdkServer;
  }


  public void setSdkServer(ParametersForTheSDKServerSidecar sdkServer) {
    this.sdkServer = sdkServer;
  }


  public V1GameServerSpec template(V1GameServerSpecTemplate template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(required = true, value = "")

  public V1GameServerSpecTemplate getTemplate() {
    return template;
  }


  public void setTemplate(V1GameServerSpecTemplate template) {
    this.template = template;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GameServerSpec v1GameServerSpec = (V1GameServerSpec) o;
    return Objects.equals(this.container, v1GameServerSpec.container) &&
        Objects.equals(this.health, v1GameServerSpec.health) &&
        Objects.equals(this.players, v1GameServerSpec.players) &&
        Objects.equals(this.ports, v1GameServerSpec.ports) &&
        Objects.equals(this.scheduling, v1GameServerSpec.scheduling) &&
        Objects.equals(this.sdkServer, v1GameServerSpec.sdkServer) &&
        Objects.equals(this.template, v1GameServerSpec.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(container, health, players, ports, scheduling, sdkServer, template);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GameServerSpec {\n");
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    health: ").append(toIndentedString(health)).append("\n");
    sb.append("    players: ").append(toIndentedString(players)).append("\n");
    sb.append("    ports: ").append(toIndentedString(ports)).append("\n");
    sb.append("    scheduling: ").append(toIndentedString(scheduling)).append("\n");
    sb.append("    sdkServer: ").append(toIndentedString(sdkServer)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

