/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.agones.models.V1GameServerSpecTemplateSpecProjectedConfigMap;
import dev.agones.models.V1GameServerSpecTemplateSpecProjectedDownwardAPI;
import dev.agones.models.V1GameServerSpecTemplateSpecProjectedSecret;
import dev.agones.models.V1GameServerSpecTemplateSpecProjectedServiceAccountToken;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1GameServerSpecTemplateSpecProjectedSources
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1GameServerSpecTemplateSpecProjectedSources {
  public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
  private V1GameServerSpecTemplateSpecProjectedConfigMap configMap;

  public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
  @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
  private V1GameServerSpecTemplateSpecProjectedDownwardAPI downwardAPI;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private V1GameServerSpecTemplateSpecProjectedSecret secret;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_TOKEN = "serviceAccountToken";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_TOKEN)
  private V1GameServerSpecTemplateSpecProjectedServiceAccountToken serviceAccountToken;


  public V1GameServerSpecTemplateSpecProjectedSources configMap(V1GameServerSpecTemplateSpecProjectedConfigMap configMap) {
    
    this.configMap = configMap;
    return this;
  }

   /**
   * Get configMap
   * @return configMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecProjectedConfigMap getConfigMap() {
    return configMap;
  }


  public void setConfigMap(V1GameServerSpecTemplateSpecProjectedConfigMap configMap) {
    this.configMap = configMap;
  }


  public V1GameServerSpecTemplateSpecProjectedSources downwardAPI(V1GameServerSpecTemplateSpecProjectedDownwardAPI downwardAPI) {
    
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * Get downwardAPI
   * @return downwardAPI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecProjectedDownwardAPI getDownwardAPI() {
    return downwardAPI;
  }


  public void setDownwardAPI(V1GameServerSpecTemplateSpecProjectedDownwardAPI downwardAPI) {
    this.downwardAPI = downwardAPI;
  }


  public V1GameServerSpecTemplateSpecProjectedSources secret(V1GameServerSpecTemplateSpecProjectedSecret secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecProjectedSecret getSecret() {
    return secret;
  }


  public void setSecret(V1GameServerSpecTemplateSpecProjectedSecret secret) {
    this.secret = secret;
  }


  public V1GameServerSpecTemplateSpecProjectedSources serviceAccountToken(V1GameServerSpecTemplateSpecProjectedServiceAccountToken serviceAccountToken) {
    
    this.serviceAccountToken = serviceAccountToken;
    return this;
  }

   /**
   * Get serviceAccountToken
   * @return serviceAccountToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecProjectedServiceAccountToken getServiceAccountToken() {
    return serviceAccountToken;
  }


  public void setServiceAccountToken(V1GameServerSpecTemplateSpecProjectedServiceAccountToken serviceAccountToken) {
    this.serviceAccountToken = serviceAccountToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GameServerSpecTemplateSpecProjectedSources v1GameServerSpecTemplateSpecProjectedSources = (V1GameServerSpecTemplateSpecProjectedSources) o;
    return Objects.equals(this.configMap, v1GameServerSpecTemplateSpecProjectedSources.configMap) &&
        Objects.equals(this.downwardAPI, v1GameServerSpecTemplateSpecProjectedSources.downwardAPI) &&
        Objects.equals(this.secret, v1GameServerSpecTemplateSpecProjectedSources.secret) &&
        Objects.equals(this.serviceAccountToken, v1GameServerSpecTemplateSpecProjectedSources.serviceAccountToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configMap, downwardAPI, secret, serviceAccountToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GameServerSpecTemplateSpecProjectedSources {\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    serviceAccountToken: ").append(toIndentedString(serviceAccountToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

