/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1GameServerAllocationPolicySpecConnectionInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1GameServerAllocationPolicySpecConnectionInfo {
  public static final String SERIALIZED_NAME_ALLOCATION_ENDPOINTS = "allocationEndpoints";
  @SerializedName(SERIALIZED_NAME_ALLOCATION_ENDPOINTS)
  private List<String> allocationEndpoints = null;

  public static final String SERIALIZED_NAME_CLUSTER_NAME = "clusterName";
  @SerializedName(SERIALIZED_NAME_CLUSTER_NAME)
  private String clusterName;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
  @SerializedName(SERIALIZED_NAME_SECRET_NAME)
  private String secretName;

  public static final String SERIALIZED_NAME_SERVER_CA = "serverCa";
  @SerializedName(SERIALIZED_NAME_SERVER_CA)
  private byte[] serverCa;


  public V1GameServerAllocationPolicySpecConnectionInfo allocationEndpoints(List<String> allocationEndpoints) {
    
    this.allocationEndpoints = allocationEndpoints;
    return this;
  }

  public V1GameServerAllocationPolicySpecConnectionInfo addAllocationEndpointsItem(String allocationEndpointsItem) {
    if (this.allocationEndpoints == null) {
      this.allocationEndpoints = new ArrayList<>();
    }
    this.allocationEndpoints.add(allocationEndpointsItem);
    return this;
  }

   /**
   * Get allocationEndpoints
   * @return allocationEndpoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAllocationEndpoints() {
    return allocationEndpoints;
  }


  public void setAllocationEndpoints(List<String> allocationEndpoints) {
    this.allocationEndpoints = allocationEndpoints;
  }


  public V1GameServerAllocationPolicySpecConnectionInfo clusterName(String clusterName) {
    
    this.clusterName = clusterName;
    return this;
  }

   /**
   * Get clusterName
   * @return clusterName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClusterName() {
    return clusterName;
  }


  public void setClusterName(String clusterName) {
    this.clusterName = clusterName;
  }


  public V1GameServerAllocationPolicySpecConnectionInfo namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @ApiModelProperty(required = true, value = "")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public V1GameServerAllocationPolicySpecConnectionInfo secretName(String secretName) {
    
    this.secretName = secretName;
    return this;
  }

   /**
   * Get secretName
   * @return secretName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSecretName() {
    return secretName;
  }


  public void setSecretName(String secretName) {
    this.secretName = secretName;
  }


  public V1GameServerAllocationPolicySpecConnectionInfo serverCa(byte[] serverCa) {
    
    this.serverCa = serverCa;
    return this;
  }

   /**
   * Get serverCa
   * @return serverCa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public byte[] getServerCa() {
    return serverCa;
  }


  public void setServerCa(byte[] serverCa) {
    this.serverCa = serverCa;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GameServerAllocationPolicySpecConnectionInfo v1GameServerAllocationPolicySpecConnectionInfo = (V1GameServerAllocationPolicySpecConnectionInfo) o;
    return Objects.equals(this.allocationEndpoints, v1GameServerAllocationPolicySpecConnectionInfo.allocationEndpoints) &&
        Objects.equals(this.clusterName, v1GameServerAllocationPolicySpecConnectionInfo.clusterName) &&
        Objects.equals(this.namespace, v1GameServerAllocationPolicySpecConnectionInfo.namespace) &&
        Objects.equals(this.secretName, v1GameServerAllocationPolicySpecConnectionInfo.secretName) &&
        Arrays.equals(this.serverCa, v1GameServerAllocationPolicySpecConnectionInfo.serverCa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allocationEndpoints, clusterName, namespace, secretName, Arrays.hashCode(serverCa));
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GameServerAllocationPolicySpecConnectionInfo {\n");
    sb.append("    allocationEndpoints: ").append(toIndentedString(allocationEndpoints)).append("\n");
    sb.append("    clusterName: ").append(toIndentedString(clusterName)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
    sb.append("    serverCa: ").append(toIndentedString(serverCa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

