/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.agones.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.agones.models.V1GameServerSpecTemplateSpecAwsElasticBlockStore;
import dev.agones.models.V1GameServerSpecTemplateSpecAzureDisk;
import dev.agones.models.V1GameServerSpecTemplateSpecAzureFile;
import dev.agones.models.V1GameServerSpecTemplateSpecCephfs;
import dev.agones.models.V1GameServerSpecTemplateSpecCinder;
import dev.agones.models.V1GameServerSpecTemplateSpecConfigMap;
import dev.agones.models.V1GameServerSpecTemplateSpecCsi;
import dev.agones.models.V1GameServerSpecTemplateSpecDownwardAPI;
import dev.agones.models.V1GameServerSpecTemplateSpecEmptyDir;
import dev.agones.models.V1GameServerSpecTemplateSpecEphemeral;
import dev.agones.models.V1GameServerSpecTemplateSpecFc;
import dev.agones.models.V1GameServerSpecTemplateSpecFlexVolume;
import dev.agones.models.V1GameServerSpecTemplateSpecFlocker;
import dev.agones.models.V1GameServerSpecTemplateSpecGcePersistentDisk;
import dev.agones.models.V1GameServerSpecTemplateSpecGitRepo;
import dev.agones.models.V1GameServerSpecTemplateSpecGlusterfs;
import dev.agones.models.V1GameServerSpecTemplateSpecHostPath;
import dev.agones.models.V1GameServerSpecTemplateSpecIscsi;
import dev.agones.models.V1GameServerSpecTemplateSpecNfs;
import dev.agones.models.V1GameServerSpecTemplateSpecPersistentVolumeClaim;
import dev.agones.models.V1GameServerSpecTemplateSpecPhotonPersistentDisk;
import dev.agones.models.V1GameServerSpecTemplateSpecPortworxVolume;
import dev.agones.models.V1GameServerSpecTemplateSpecProjected;
import dev.agones.models.V1GameServerSpecTemplateSpecQuobyte;
import dev.agones.models.V1GameServerSpecTemplateSpecRbd;
import dev.agones.models.V1GameServerSpecTemplateSpecScaleIO;
import dev.agones.models.V1GameServerSpecTemplateSpecSecret;
import dev.agones.models.V1GameServerSpecTemplateSpecStorageos;
import dev.agones.models.V1GameServerSpecTemplateSpecVsphereVolume;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1GameServerSpecTemplateSpecVolumes
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-16T08:25:17.075Z[Etc/UTC]")
public class V1GameServerSpecTemplateSpecVolumes {
  public static final String SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE = "awsElasticBlockStore";
  @SerializedName(SERIALIZED_NAME_AWS_ELASTIC_BLOCK_STORE)
  private V1GameServerSpecTemplateSpecAwsElasticBlockStore awsElasticBlockStore;

  public static final String SERIALIZED_NAME_AZURE_DISK = "azureDisk";
  @SerializedName(SERIALIZED_NAME_AZURE_DISK)
  private V1GameServerSpecTemplateSpecAzureDisk azureDisk;

  public static final String SERIALIZED_NAME_AZURE_FILE = "azureFile";
  @SerializedName(SERIALIZED_NAME_AZURE_FILE)
  private V1GameServerSpecTemplateSpecAzureFile azureFile;

  public static final String SERIALIZED_NAME_CEPHFS = "cephfs";
  @SerializedName(SERIALIZED_NAME_CEPHFS)
  private V1GameServerSpecTemplateSpecCephfs cephfs;

  public static final String SERIALIZED_NAME_CINDER = "cinder";
  @SerializedName(SERIALIZED_NAME_CINDER)
  private V1GameServerSpecTemplateSpecCinder cinder;

  public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
  private V1GameServerSpecTemplateSpecConfigMap configMap;

  public static final String SERIALIZED_NAME_CSI = "csi";
  @SerializedName(SERIALIZED_NAME_CSI)
  private V1GameServerSpecTemplateSpecCsi csi;

  public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
  @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
  private V1GameServerSpecTemplateSpecDownwardAPI downwardAPI;

  public static final String SERIALIZED_NAME_EMPTY_DIR = "emptyDir";
  @SerializedName(SERIALIZED_NAME_EMPTY_DIR)
  private V1GameServerSpecTemplateSpecEmptyDir emptyDir;

  public static final String SERIALIZED_NAME_EPHEMERAL = "ephemeral";
  @SerializedName(SERIALIZED_NAME_EPHEMERAL)
  private V1GameServerSpecTemplateSpecEphemeral ephemeral;

  public static final String SERIALIZED_NAME_FC = "fc";
  @SerializedName(SERIALIZED_NAME_FC)
  private V1GameServerSpecTemplateSpecFc fc;

  public static final String SERIALIZED_NAME_FLEX_VOLUME = "flexVolume";
  @SerializedName(SERIALIZED_NAME_FLEX_VOLUME)
  private V1GameServerSpecTemplateSpecFlexVolume flexVolume;

  public static final String SERIALIZED_NAME_FLOCKER = "flocker";
  @SerializedName(SERIALIZED_NAME_FLOCKER)
  private V1GameServerSpecTemplateSpecFlocker flocker;

  public static final String SERIALIZED_NAME_GCE_PERSISTENT_DISK = "gcePersistentDisk";
  @SerializedName(SERIALIZED_NAME_GCE_PERSISTENT_DISK)
  private V1GameServerSpecTemplateSpecGcePersistentDisk gcePersistentDisk;

  public static final String SERIALIZED_NAME_GIT_REPO = "gitRepo";
  @SerializedName(SERIALIZED_NAME_GIT_REPO)
  private V1GameServerSpecTemplateSpecGitRepo gitRepo;

  public static final String SERIALIZED_NAME_GLUSTERFS = "glusterfs";
  @SerializedName(SERIALIZED_NAME_GLUSTERFS)
  private V1GameServerSpecTemplateSpecGlusterfs glusterfs;

  public static final String SERIALIZED_NAME_HOST_PATH = "hostPath";
  @SerializedName(SERIALIZED_NAME_HOST_PATH)
  private V1GameServerSpecTemplateSpecHostPath hostPath;

  public static final String SERIALIZED_NAME_ISCSI = "iscsi";
  @SerializedName(SERIALIZED_NAME_ISCSI)
  private V1GameServerSpecTemplateSpecIscsi iscsi;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NFS = "nfs";
  @SerializedName(SERIALIZED_NAME_NFS)
  private V1GameServerSpecTemplateSpecNfs nfs;

  public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM = "persistentVolumeClaim";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM)
  private V1GameServerSpecTemplateSpecPersistentVolumeClaim persistentVolumeClaim;

  public static final String SERIALIZED_NAME_PHOTON_PERSISTENT_DISK = "photonPersistentDisk";
  @SerializedName(SERIALIZED_NAME_PHOTON_PERSISTENT_DISK)
  private V1GameServerSpecTemplateSpecPhotonPersistentDisk photonPersistentDisk;

  public static final String SERIALIZED_NAME_PORTWORX_VOLUME = "portworxVolume";
  @SerializedName(SERIALIZED_NAME_PORTWORX_VOLUME)
  private V1GameServerSpecTemplateSpecPortworxVolume portworxVolume;

  public static final String SERIALIZED_NAME_PROJECTED = "projected";
  @SerializedName(SERIALIZED_NAME_PROJECTED)
  private V1GameServerSpecTemplateSpecProjected projected;

  public static final String SERIALIZED_NAME_QUOBYTE = "quobyte";
  @SerializedName(SERIALIZED_NAME_QUOBYTE)
  private V1GameServerSpecTemplateSpecQuobyte quobyte;

  public static final String SERIALIZED_NAME_RBD = "rbd";
  @SerializedName(SERIALIZED_NAME_RBD)
  private V1GameServerSpecTemplateSpecRbd rbd;

  public static final String SERIALIZED_NAME_SCALE_I_O = "scaleIO";
  @SerializedName(SERIALIZED_NAME_SCALE_I_O)
  private V1GameServerSpecTemplateSpecScaleIO scaleIO;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private V1GameServerSpecTemplateSpecSecret secret;

  public static final String SERIALIZED_NAME_STORAGEOS = "storageos";
  @SerializedName(SERIALIZED_NAME_STORAGEOS)
  private V1GameServerSpecTemplateSpecStorageos storageos;

  public static final String SERIALIZED_NAME_VSPHERE_VOLUME = "vsphereVolume";
  @SerializedName(SERIALIZED_NAME_VSPHERE_VOLUME)
  private V1GameServerSpecTemplateSpecVsphereVolume vsphereVolume;


  public V1GameServerSpecTemplateSpecVolumes awsElasticBlockStore(V1GameServerSpecTemplateSpecAwsElasticBlockStore awsElasticBlockStore) {
    
    this.awsElasticBlockStore = awsElasticBlockStore;
    return this;
  }

   /**
   * Get awsElasticBlockStore
   * @return awsElasticBlockStore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecAwsElasticBlockStore getAwsElasticBlockStore() {
    return awsElasticBlockStore;
  }


  public void setAwsElasticBlockStore(V1GameServerSpecTemplateSpecAwsElasticBlockStore awsElasticBlockStore) {
    this.awsElasticBlockStore = awsElasticBlockStore;
  }


  public V1GameServerSpecTemplateSpecVolumes azureDisk(V1GameServerSpecTemplateSpecAzureDisk azureDisk) {
    
    this.azureDisk = azureDisk;
    return this;
  }

   /**
   * Get azureDisk
   * @return azureDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecAzureDisk getAzureDisk() {
    return azureDisk;
  }


  public void setAzureDisk(V1GameServerSpecTemplateSpecAzureDisk azureDisk) {
    this.azureDisk = azureDisk;
  }


  public V1GameServerSpecTemplateSpecVolumes azureFile(V1GameServerSpecTemplateSpecAzureFile azureFile) {
    
    this.azureFile = azureFile;
    return this;
  }

   /**
   * Get azureFile
   * @return azureFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecAzureFile getAzureFile() {
    return azureFile;
  }


  public void setAzureFile(V1GameServerSpecTemplateSpecAzureFile azureFile) {
    this.azureFile = azureFile;
  }


  public V1GameServerSpecTemplateSpecVolumes cephfs(V1GameServerSpecTemplateSpecCephfs cephfs) {
    
    this.cephfs = cephfs;
    return this;
  }

   /**
   * Get cephfs
   * @return cephfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecCephfs getCephfs() {
    return cephfs;
  }


  public void setCephfs(V1GameServerSpecTemplateSpecCephfs cephfs) {
    this.cephfs = cephfs;
  }


  public V1GameServerSpecTemplateSpecVolumes cinder(V1GameServerSpecTemplateSpecCinder cinder) {
    
    this.cinder = cinder;
    return this;
  }

   /**
   * Get cinder
   * @return cinder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecCinder getCinder() {
    return cinder;
  }


  public void setCinder(V1GameServerSpecTemplateSpecCinder cinder) {
    this.cinder = cinder;
  }


  public V1GameServerSpecTemplateSpecVolumes configMap(V1GameServerSpecTemplateSpecConfigMap configMap) {
    
    this.configMap = configMap;
    return this;
  }

   /**
   * Get configMap
   * @return configMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecConfigMap getConfigMap() {
    return configMap;
  }


  public void setConfigMap(V1GameServerSpecTemplateSpecConfigMap configMap) {
    this.configMap = configMap;
  }


  public V1GameServerSpecTemplateSpecVolumes csi(V1GameServerSpecTemplateSpecCsi csi) {
    
    this.csi = csi;
    return this;
  }

   /**
   * Get csi
   * @return csi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecCsi getCsi() {
    return csi;
  }


  public void setCsi(V1GameServerSpecTemplateSpecCsi csi) {
    this.csi = csi;
  }


  public V1GameServerSpecTemplateSpecVolumes downwardAPI(V1GameServerSpecTemplateSpecDownwardAPI downwardAPI) {
    
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * Get downwardAPI
   * @return downwardAPI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecDownwardAPI getDownwardAPI() {
    return downwardAPI;
  }


  public void setDownwardAPI(V1GameServerSpecTemplateSpecDownwardAPI downwardAPI) {
    this.downwardAPI = downwardAPI;
  }


  public V1GameServerSpecTemplateSpecVolumes emptyDir(V1GameServerSpecTemplateSpecEmptyDir emptyDir) {
    
    this.emptyDir = emptyDir;
    return this;
  }

   /**
   * Get emptyDir
   * @return emptyDir
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecEmptyDir getEmptyDir() {
    return emptyDir;
  }


  public void setEmptyDir(V1GameServerSpecTemplateSpecEmptyDir emptyDir) {
    this.emptyDir = emptyDir;
  }


  public V1GameServerSpecTemplateSpecVolumes ephemeral(V1GameServerSpecTemplateSpecEphemeral ephemeral) {
    
    this.ephemeral = ephemeral;
    return this;
  }

   /**
   * Get ephemeral
   * @return ephemeral
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecEphemeral getEphemeral() {
    return ephemeral;
  }


  public void setEphemeral(V1GameServerSpecTemplateSpecEphemeral ephemeral) {
    this.ephemeral = ephemeral;
  }


  public V1GameServerSpecTemplateSpecVolumes fc(V1GameServerSpecTemplateSpecFc fc) {
    
    this.fc = fc;
    return this;
  }

   /**
   * Get fc
   * @return fc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecFc getFc() {
    return fc;
  }


  public void setFc(V1GameServerSpecTemplateSpecFc fc) {
    this.fc = fc;
  }


  public V1GameServerSpecTemplateSpecVolumes flexVolume(V1GameServerSpecTemplateSpecFlexVolume flexVolume) {
    
    this.flexVolume = flexVolume;
    return this;
  }

   /**
   * Get flexVolume
   * @return flexVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecFlexVolume getFlexVolume() {
    return flexVolume;
  }


  public void setFlexVolume(V1GameServerSpecTemplateSpecFlexVolume flexVolume) {
    this.flexVolume = flexVolume;
  }


  public V1GameServerSpecTemplateSpecVolumes flocker(V1GameServerSpecTemplateSpecFlocker flocker) {
    
    this.flocker = flocker;
    return this;
  }

   /**
   * Get flocker
   * @return flocker
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecFlocker getFlocker() {
    return flocker;
  }


  public void setFlocker(V1GameServerSpecTemplateSpecFlocker flocker) {
    this.flocker = flocker;
  }


  public V1GameServerSpecTemplateSpecVolumes gcePersistentDisk(V1GameServerSpecTemplateSpecGcePersistentDisk gcePersistentDisk) {
    
    this.gcePersistentDisk = gcePersistentDisk;
    return this;
  }

   /**
   * Get gcePersistentDisk
   * @return gcePersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecGcePersistentDisk getGcePersistentDisk() {
    return gcePersistentDisk;
  }


  public void setGcePersistentDisk(V1GameServerSpecTemplateSpecGcePersistentDisk gcePersistentDisk) {
    this.gcePersistentDisk = gcePersistentDisk;
  }


  public V1GameServerSpecTemplateSpecVolumes gitRepo(V1GameServerSpecTemplateSpecGitRepo gitRepo) {
    
    this.gitRepo = gitRepo;
    return this;
  }

   /**
   * Get gitRepo
   * @return gitRepo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecGitRepo getGitRepo() {
    return gitRepo;
  }


  public void setGitRepo(V1GameServerSpecTemplateSpecGitRepo gitRepo) {
    this.gitRepo = gitRepo;
  }


  public V1GameServerSpecTemplateSpecVolumes glusterfs(V1GameServerSpecTemplateSpecGlusterfs glusterfs) {
    
    this.glusterfs = glusterfs;
    return this;
  }

   /**
   * Get glusterfs
   * @return glusterfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecGlusterfs getGlusterfs() {
    return glusterfs;
  }


  public void setGlusterfs(V1GameServerSpecTemplateSpecGlusterfs glusterfs) {
    this.glusterfs = glusterfs;
  }


  public V1GameServerSpecTemplateSpecVolumes hostPath(V1GameServerSpecTemplateSpecHostPath hostPath) {
    
    this.hostPath = hostPath;
    return this;
  }

   /**
   * Get hostPath
   * @return hostPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecHostPath getHostPath() {
    return hostPath;
  }


  public void setHostPath(V1GameServerSpecTemplateSpecHostPath hostPath) {
    this.hostPath = hostPath;
  }


  public V1GameServerSpecTemplateSpecVolumes iscsi(V1GameServerSpecTemplateSpecIscsi iscsi) {
    
    this.iscsi = iscsi;
    return this;
  }

   /**
   * Get iscsi
   * @return iscsi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecIscsi getIscsi() {
    return iscsi;
  }


  public void setIscsi(V1GameServerSpecTemplateSpecIscsi iscsi) {
    this.iscsi = iscsi;
  }


  public V1GameServerSpecTemplateSpecVolumes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Volume&#39;s name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Volume's name. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1GameServerSpecTemplateSpecVolumes nfs(V1GameServerSpecTemplateSpecNfs nfs) {
    
    this.nfs = nfs;
    return this;
  }

   /**
   * Get nfs
   * @return nfs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecNfs getNfs() {
    return nfs;
  }


  public void setNfs(V1GameServerSpecTemplateSpecNfs nfs) {
    this.nfs = nfs;
  }


  public V1GameServerSpecTemplateSpecVolumes persistentVolumeClaim(V1GameServerSpecTemplateSpecPersistentVolumeClaim persistentVolumeClaim) {
    
    this.persistentVolumeClaim = persistentVolumeClaim;
    return this;
  }

   /**
   * Get persistentVolumeClaim
   * @return persistentVolumeClaim
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecPersistentVolumeClaim getPersistentVolumeClaim() {
    return persistentVolumeClaim;
  }


  public void setPersistentVolumeClaim(V1GameServerSpecTemplateSpecPersistentVolumeClaim persistentVolumeClaim) {
    this.persistentVolumeClaim = persistentVolumeClaim;
  }


  public V1GameServerSpecTemplateSpecVolumes photonPersistentDisk(V1GameServerSpecTemplateSpecPhotonPersistentDisk photonPersistentDisk) {
    
    this.photonPersistentDisk = photonPersistentDisk;
    return this;
  }

   /**
   * Get photonPersistentDisk
   * @return photonPersistentDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecPhotonPersistentDisk getPhotonPersistentDisk() {
    return photonPersistentDisk;
  }


  public void setPhotonPersistentDisk(V1GameServerSpecTemplateSpecPhotonPersistentDisk photonPersistentDisk) {
    this.photonPersistentDisk = photonPersistentDisk;
  }


  public V1GameServerSpecTemplateSpecVolumes portworxVolume(V1GameServerSpecTemplateSpecPortworxVolume portworxVolume) {
    
    this.portworxVolume = portworxVolume;
    return this;
  }

   /**
   * Get portworxVolume
   * @return portworxVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecPortworxVolume getPortworxVolume() {
    return portworxVolume;
  }


  public void setPortworxVolume(V1GameServerSpecTemplateSpecPortworxVolume portworxVolume) {
    this.portworxVolume = portworxVolume;
  }


  public V1GameServerSpecTemplateSpecVolumes projected(V1GameServerSpecTemplateSpecProjected projected) {
    
    this.projected = projected;
    return this;
  }

   /**
   * Get projected
   * @return projected
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecProjected getProjected() {
    return projected;
  }


  public void setProjected(V1GameServerSpecTemplateSpecProjected projected) {
    this.projected = projected;
  }


  public V1GameServerSpecTemplateSpecVolumes quobyte(V1GameServerSpecTemplateSpecQuobyte quobyte) {
    
    this.quobyte = quobyte;
    return this;
  }

   /**
   * Get quobyte
   * @return quobyte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecQuobyte getQuobyte() {
    return quobyte;
  }


  public void setQuobyte(V1GameServerSpecTemplateSpecQuobyte quobyte) {
    this.quobyte = quobyte;
  }


  public V1GameServerSpecTemplateSpecVolumes rbd(V1GameServerSpecTemplateSpecRbd rbd) {
    
    this.rbd = rbd;
    return this;
  }

   /**
   * Get rbd
   * @return rbd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecRbd getRbd() {
    return rbd;
  }


  public void setRbd(V1GameServerSpecTemplateSpecRbd rbd) {
    this.rbd = rbd;
  }


  public V1GameServerSpecTemplateSpecVolumes scaleIO(V1GameServerSpecTemplateSpecScaleIO scaleIO) {
    
    this.scaleIO = scaleIO;
    return this;
  }

   /**
   * Get scaleIO
   * @return scaleIO
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecScaleIO getScaleIO() {
    return scaleIO;
  }


  public void setScaleIO(V1GameServerSpecTemplateSpecScaleIO scaleIO) {
    this.scaleIO = scaleIO;
  }


  public V1GameServerSpecTemplateSpecVolumes secret(V1GameServerSpecTemplateSpecSecret secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecSecret getSecret() {
    return secret;
  }


  public void setSecret(V1GameServerSpecTemplateSpecSecret secret) {
    this.secret = secret;
  }


  public V1GameServerSpecTemplateSpecVolumes storageos(V1GameServerSpecTemplateSpecStorageos storageos) {
    
    this.storageos = storageos;
    return this;
  }

   /**
   * Get storageos
   * @return storageos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecStorageos getStorageos() {
    return storageos;
  }


  public void setStorageos(V1GameServerSpecTemplateSpecStorageos storageos) {
    this.storageos = storageos;
  }


  public V1GameServerSpecTemplateSpecVolumes vsphereVolume(V1GameServerSpecTemplateSpecVsphereVolume vsphereVolume) {
    
    this.vsphereVolume = vsphereVolume;
    return this;
  }

   /**
   * Get vsphereVolume
   * @return vsphereVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1GameServerSpecTemplateSpecVsphereVolume getVsphereVolume() {
    return vsphereVolume;
  }


  public void setVsphereVolume(V1GameServerSpecTemplateSpecVsphereVolume vsphereVolume) {
    this.vsphereVolume = vsphereVolume;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1GameServerSpecTemplateSpecVolumes v1GameServerSpecTemplateSpecVolumes = (V1GameServerSpecTemplateSpecVolumes) o;
    return Objects.equals(this.awsElasticBlockStore, v1GameServerSpecTemplateSpecVolumes.awsElasticBlockStore) &&
        Objects.equals(this.azureDisk, v1GameServerSpecTemplateSpecVolumes.azureDisk) &&
        Objects.equals(this.azureFile, v1GameServerSpecTemplateSpecVolumes.azureFile) &&
        Objects.equals(this.cephfs, v1GameServerSpecTemplateSpecVolumes.cephfs) &&
        Objects.equals(this.cinder, v1GameServerSpecTemplateSpecVolumes.cinder) &&
        Objects.equals(this.configMap, v1GameServerSpecTemplateSpecVolumes.configMap) &&
        Objects.equals(this.csi, v1GameServerSpecTemplateSpecVolumes.csi) &&
        Objects.equals(this.downwardAPI, v1GameServerSpecTemplateSpecVolumes.downwardAPI) &&
        Objects.equals(this.emptyDir, v1GameServerSpecTemplateSpecVolumes.emptyDir) &&
        Objects.equals(this.ephemeral, v1GameServerSpecTemplateSpecVolumes.ephemeral) &&
        Objects.equals(this.fc, v1GameServerSpecTemplateSpecVolumes.fc) &&
        Objects.equals(this.flexVolume, v1GameServerSpecTemplateSpecVolumes.flexVolume) &&
        Objects.equals(this.flocker, v1GameServerSpecTemplateSpecVolumes.flocker) &&
        Objects.equals(this.gcePersistentDisk, v1GameServerSpecTemplateSpecVolumes.gcePersistentDisk) &&
        Objects.equals(this.gitRepo, v1GameServerSpecTemplateSpecVolumes.gitRepo) &&
        Objects.equals(this.glusterfs, v1GameServerSpecTemplateSpecVolumes.glusterfs) &&
        Objects.equals(this.hostPath, v1GameServerSpecTemplateSpecVolumes.hostPath) &&
        Objects.equals(this.iscsi, v1GameServerSpecTemplateSpecVolumes.iscsi) &&
        Objects.equals(this.name, v1GameServerSpecTemplateSpecVolumes.name) &&
        Objects.equals(this.nfs, v1GameServerSpecTemplateSpecVolumes.nfs) &&
        Objects.equals(this.persistentVolumeClaim, v1GameServerSpecTemplateSpecVolumes.persistentVolumeClaim) &&
        Objects.equals(this.photonPersistentDisk, v1GameServerSpecTemplateSpecVolumes.photonPersistentDisk) &&
        Objects.equals(this.portworxVolume, v1GameServerSpecTemplateSpecVolumes.portworxVolume) &&
        Objects.equals(this.projected, v1GameServerSpecTemplateSpecVolumes.projected) &&
        Objects.equals(this.quobyte, v1GameServerSpecTemplateSpecVolumes.quobyte) &&
        Objects.equals(this.rbd, v1GameServerSpecTemplateSpecVolumes.rbd) &&
        Objects.equals(this.scaleIO, v1GameServerSpecTemplateSpecVolumes.scaleIO) &&
        Objects.equals(this.secret, v1GameServerSpecTemplateSpecVolumes.secret) &&
        Objects.equals(this.storageos, v1GameServerSpecTemplateSpecVolumes.storageos) &&
        Objects.equals(this.vsphereVolume, v1GameServerSpecTemplateSpecVolumes.vsphereVolume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(awsElasticBlockStore, azureDisk, azureFile, cephfs, cinder, configMap, csi, downwardAPI, emptyDir, ephemeral, fc, flexVolume, flocker, gcePersistentDisk, gitRepo, glusterfs, hostPath, iscsi, name, nfs, persistentVolumeClaim, photonPersistentDisk, portworxVolume, projected, quobyte, rbd, scaleIO, secret, storageos, vsphereVolume);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1GameServerSpecTemplateSpecVolumes {\n");
    sb.append("    awsElasticBlockStore: ").append(toIndentedString(awsElasticBlockStore)).append("\n");
    sb.append("    azureDisk: ").append(toIndentedString(azureDisk)).append("\n");
    sb.append("    azureFile: ").append(toIndentedString(azureFile)).append("\n");
    sb.append("    cephfs: ").append(toIndentedString(cephfs)).append("\n");
    sb.append("    cinder: ").append(toIndentedString(cinder)).append("\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    csi: ").append(toIndentedString(csi)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    emptyDir: ").append(toIndentedString(emptyDir)).append("\n");
    sb.append("    ephemeral: ").append(toIndentedString(ephemeral)).append("\n");
    sb.append("    fc: ").append(toIndentedString(fc)).append("\n");
    sb.append("    flexVolume: ").append(toIndentedString(flexVolume)).append("\n");
    sb.append("    flocker: ").append(toIndentedString(flocker)).append("\n");
    sb.append("    gcePersistentDisk: ").append(toIndentedString(gcePersistentDisk)).append("\n");
    sb.append("    gitRepo: ").append(toIndentedString(gitRepo)).append("\n");
    sb.append("    glusterfs: ").append(toIndentedString(glusterfs)).append("\n");
    sb.append("    hostPath: ").append(toIndentedString(hostPath)).append("\n");
    sb.append("    iscsi: ").append(toIndentedString(iscsi)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nfs: ").append(toIndentedString(nfs)).append("\n");
    sb.append("    persistentVolumeClaim: ").append(toIndentedString(persistentVolumeClaim)).append("\n");
    sb.append("    photonPersistentDisk: ").append(toIndentedString(photonPersistentDisk)).append("\n");
    sb.append("    portworxVolume: ").append(toIndentedString(portworxVolume)).append("\n");
    sb.append("    projected: ").append(toIndentedString(projected)).append("\n");
    sb.append("    quobyte: ").append(toIndentedString(quobyte)).append("\n");
    sb.append("    rbd: ").append(toIndentedString(rbd)).append("\n");
    sb.append("    scaleIO: ").append(toIndentedString(scaleIO)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    storageos: ").append(toIndentedString(storageos)).append("\n");
    sb.append("    vsphereVolume: ").append(toIndentedString(vsphereVolume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

